part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const LOGIN_OR_SIGN_UP = _Paths.LOGIN_OR_SIGN_UP;
  static const LOGIN = _Paths.LOGIN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const CONNECTION_FAILED = _Paths.CONNECTION_FAILED;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const BOTTOM_NAV_BAR = _Paths.BOTTOM_NAV_BAR;
  static const PROFILE = _Paths.PROFILE;
  static const MESSAGES = _Paths.MESSAGES;
  static const ORDERS = _Paths.ORDERS;
  static const ORDER_DARS = _Paths.ORDER_DARS;
  static const DEPENDENTS = _Paths.DEPENDENTS;
  static const ADD_NEW_DEPENDENT = _Paths.ADD_NEW_DEPENDENT;
  static const SETTINGS = _Paths.SETTINGS;
  static const TECHNICAL_SUPPORT = _Paths.TECHNICAL_SUPPORT;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const DARS_TEACHERS = _Paths.DARS_TEACHERS;
  static const DARS_DETAILS = _Paths.DARS_DETAILS;
  static const TEACHER_DETAILS = _Paths.TEACHER_DETAILS;
  static const ABOUT_DARS = _Paths.ABOUT_DARS;
  static const WALLET = _Paths.WALLET;
  static const ADD_PAYMENT_WAY = _Paths.ADD_PAYMENT_WAY;
  static const STATIC_PAGE = _Paths.STATIC_PAGE;
  static const CHAT = _Paths.CHAT;
  static const VERIFY_OTP = _Paths.VERIFY_OTP;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const PROFILE_INFORMATION = _Paths.PROFILE_INFORMATION;
  static const VERIFY_ACCOUNT = _Paths.VERIFY_ACCOUNT;
  static const PREFERRED_TEACHERS = _Paths.PREFERRED_TEACHERS;
  static const ADDRESSES = _Paths.ADDRESSES;
  static const ADD_NEW_ADDRESS = _Paths.ADD_NEW_ADDRESS;
  static const EDIT_ADDRESS = _Paths.EDIT_ADDRESS;
  static const EDIT_DEPENDENT = _Paths.EDIT_DEPENDENT;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const LOGIN_OR_SIGN_UP = '/login-or-sign-up';
  static const LOGIN = '/login';
  static const SIGN_UP = '/sign-up';
  static const CONNECTION_FAILED = '/connection-failed';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const BOTTOM_NAV_BAR = '/bottom-nav-bar';
  static const PROFILE = '/profile';
  static const MESSAGES = '/messages';
  static const ORDERS = '/orders';
  static const ORDER_DARS = '/order-dars';
  static const DEPENDENTS = '/dependents';
  static const ADD_NEW_DEPENDENT = '/add-new-dependent';
  static const SETTINGS = '/settings';
  static const TECHNICAL_SUPPORT = '/technical-support';
  static const NOTIFICATIONS = '/notifications';
  static const DARS_TEACHERS = '/dars-teachers';
  static const DARS_DETAILS = '/dars-details';
  static const TEACHER_DETAILS = '/teacher-details';
  static const ABOUT_DARS = '/about-dars';
  static const WALLET = '/wallet';
  static const ADD_PAYMENT_WAY = '/add-payment-way';
  static const STATIC_PAGE = '/static-page';
  static const CHAT = '/chat';
  static const VERIFY_OTP = '/verify-otp';
  static const RESET_PASSWORD = '/reset-password';
  static const EDIT_PROFILE = '/edit-profile';
  static const PROFILE_INFORMATION = '/profile-information';
  static const VERIFY_ACCOUNT = '/verify-account';
  static const PREFERRED_TEACHERS = '/preferred-teachers';
  static const ADDRESSES = '/addresses';
  static const ADD_NEW_ADDRESS = '/add-new-address';
  static const EDIT_ADDRESS = '/edit-address';
  static const EDIT_DEPENDENT = '/edit-dependent';
}
